spring:
  application:
    name: backend
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:h2:tcp://localhost//Volumes/personal/development/project/tourapi-24/backend/h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

jwt:
  expiration: 3600000

springdoc:
  api-docs:
    path: /docs/api
  swagger-ui:
    path: /docs/swagger-ui.html
    operationsSorter: method
